apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30003
  selector:
    app: prometheus
