apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
    nodePort: 30007
