apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
  namespace: prometheus
data:
  key: QVFBeUdLTmkvQlExS3hBQXlqVGRBaXNMY2hUMy9YbW9XQ3YyeUE9PQo=
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: prometheus
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 10.10.36.211:6789
      - 10.10.36.212:6789
      - 10.10.36.213:6789
    #path: /cephfs
    user: admin
    readOnly: false
    secretRef:
        name: prometheus-secret
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteMany
  volumeName: prometheus-pv
  resources:
    requests:
      storage: 20Gi
